//http://userjs.up.seesaa.net/js/bookmarklet.html

// July 11: extracted user-key to uk variable
javascript:function%20_readlater(){var%20uk='rUffwEbLWzkz';var%20d=document,w=window,e=w.getSelection,k=d.getSelection,x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:0)),f='http://www.instapaper.com/b',e=encodeURIComponent;if(/www\.google\.com\/reader\/i\//.test(d.location)){var%20n=d.getElementById('entries').childNodes,l=null,h=null;for(var%20i=0;i<n.length;i++){if(/expanded/.test(n[i].className)){l=n[i];break;}}var%20t=l.getElementsByTagName('span');for(var%20i=0;i<t.length;i++){if(/item-title/.test(t[i].className)){l.title=t[i].textContent;break;}}var%20h=l.getElementsByTagName('a');for(var%20i=h.length-1;i>=0;i--){if(/See%20original/.test(h[i].textContent)&&h[i].href){l.href=h[i].href;break;}}var%20p='?v=4&k='+uk+'&u='+e(l.href)+'&t='+e(l.title)+'&s='+e(s),u=f+p;}else%20if(/www\.google\.com\/reader/.test(d.location)&&typeof(window.getPermalink)=='function'&&getPermalink()!=null){var%20l=getPermalink();l.href=l.url;var%20p='?v=4&k='+uk+'&u='+e(l.href)+'&t='+e(l.title)+'&s='+e(s),u=f+p;}else{var%20l=d.location,p='?v=4&k='+uk+'&u='+e(l.href)+'&t='+e(d.title)+'&s='+e(s),u=f+p;}try{if(!/^(.*\.)?instapaper([^.]*)?$/.test(l.host))throw(0);iptstbt();}catch(z){a=function(){if(!w.open(u,'t','toolbar=0,resizable=0,status=1,width=250,height=150'))d.location.href=u;};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else%20a();}}_readlater();void(0)


// Before July 11

javascript:function%20_readlater(){var%20d=document,w=window,e=w.getSelection,k=d.getSelection,x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:0)),f='http://www.instapaper.com/b',e=encodeURIComponent;if(/www\.google\.com\/reader\/i\//.test(d.location)){var%20n=d.getElementById('entries').childNodes,l=null,h=null;for(var%20i=0;i<n.length;i++){if(/expanded/.test(n[i].className)){l=n[i];break;}}var%20t=l.getElementsByTagName('span');for(var%20i=0;i<t.length;i++){if(/item-title/.test(t[i].className)){l.title=t[i].textContent;break;}}var%20h=l.getElementsByTagName('a');for(var%20i=h.length-1;i>=0;i--){if(/See%20original/.test(h[i].textContent)%20&&%20h[i].href){l.href=h[i].href;break;}}var%20p='?v=4&k=rUffwEbLWzkz&u='+e(l.href)+'&t='+e(l.title)+'&s='+e(s),u=f+p;}else%20if(/www\.google\.com\/reader/.test(d.location)%20&&%20typeof(window.getPermalink)=='function'%20&&%20getPermalink()!=null){var%20l=getPermalink();l.href=l.url;var%20p='?v=4&k=rUffwEbLWzkz&u='+e(l.href)+'&t='+e(l.title)+'&s='+e(s),u=f+p;}else{var%20l=d.location,p='?v=4&k=rUffwEbLWzkz&u='+e(l.href)+'&t='+e(d.title)+'&s='+e(s),u=f+p;}try{if(!/^(.*\.)?instapaper([^.]*)?$/.test(l.host))throw(0);iptstbt();}catch(z){a=function(){if(!w.open(u,'t','toolbar=0,resizable=0,status=1,width=250,height=150'))d.location.href=u;};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else%20a();}}_readlater();void(0)

javascript:function%20_readlater(){var%20d=document,w=window;if(/www\.google\.com\/reader/.test(d.location)%20&&%20typeof(window.getPermalink)=='function'%20&&%20getPermalink()!=%20null){var%20e=w.getSelection,k=d.getSelection,x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:0)),f='http://www.instapaper.com/b',l=getPermalink();l.href=l.url;var%20e=encodeURIComponent,p='?v=4&k=rUffwEbLWzkz&u='+e(l.href)+'&t='+e(l.title)+'&s='+e(s),u=f+p;l=d.location;}else{var%20e=w.getSelection,k=d.getSelection,x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:0)),f='http://www.instapaper.com/b',l=d.location,e=encodeURIComponent,p='?v=4&k=rUffwEbLWzkz&u='+e(l.href)+'&t='+e(d.title)+'&s='+e(s),u=f+p;}try{if(!/^(.*\.)?instapaper([^.]*)?$/.test(l.host))throw(0);iptstbt();}catch(z){a%20=function(){if(!w.open(u,'t','toolbar=0,resizable=0,status=1,width=250,height=150'))l.href=u;};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else%20a();}}_readlater();void(0)

javascript:function%20_readlater(){var%20d=document,w=window;if(/www\.google\.com\/reader\/i\//.test(d.location)){var%20n=d.getElementById('entries').childNodes,l=null,h=null;var%20e=w.getSelection,k=d.getSelection,x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:0)),f='http://www.instapaper.com/b';for(var%20i=0;i<n.length;i++){if(/expanded/.test(n[i].className)){l=n[i];%20break;}}var%20t=l.getElementsByTagName('span');for(var%20i=0;i<t.length;i++){if(/item-title/.test(t[i].className)){l.title=t[i].textContent;break;}}var%20h=l.getElementsByTagName('a');for(var%20i=h.length-1;i>=0;i--){if(/See%20original/.test(h[i].textContent)&&h[i].href){l.href=h[i].href;break;}}var%20e=encodeURIComponent,p='?v=4&k=rUffwEbLWzkz&u='+e(l.href)+'&t='+e(l.title)+'&s='+e(s),u=f+p;l=d.location;}else%20if(/www\.google\.com\/reader/.test(d.location)%20&&%20typeof(window.getPermalink)=='function'%20&&%20getPermalink()!=null){var%20e=w.getSelection,k=d.getSelection,x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:0)),f='http://www.instapaper.com/b',l=getPermalink();l.href=l.url;var%20e=encodeURIComponent,p='?v=4&k=rUffwEbLWzkz&u='+e(l.href)+'&t='+e(l.title)+'&s='+e(s),u=f+p;l=d.location;}else{var%20e=w.getSelection,k=d.getSelection,x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:0)),f='http://www.instapaper.com/b',l=d.location,e=encodeURIComponent,p='?v=4&k=rUffwEbLWzkz&u='+e(l.href)+'&t='+e(d.title)+'&s='+e(s),u=f+p;}try{if(!/^(.*\.)?instapaper([^.]*)?$/.test(l.host))throw(0);iptstbt();}catch(z){a=function(){if(!w.open(u,'t','toolbar=0,resizable=0,status=1,width=250,height=150'))l.href=u;};if(/Firefox/.test(navigator.userAgent))setTimeout(a,0);else%20a();}}_readlater();void(0)